
export const GET_INTERACTIONS = "GET_INTERACTIONS"
export const GET_INTERACTIONS_SUCCESS = "GET_INTERACTIONS_SUCCESS"
export const GET_INTERACTIONS_FAIL = "GET_INTERACTIONS_FAIL"



export const ADD_NEW_INTERACTION = "ADD_NEW_INTERACTION"
export const ADD_INTERACTION_SUCCESS = "ADD_INTERACTION_SUCCESS"
export const ADD_INTERACTION_FAIL = "ADD_INTERACTION_FAIL"


export const UPDATE_INTERACTION = "UPDATE_INTERACTION"
export const UPDATE_INTERACTION_SUCCESS = "UPDATE_INTERACTION_SUCCESS"
export const UPDATE_INTERACTION_FAIL = "UPDATE_INTERACTION_FAIL"
