
export const GET_SALES = "GET_SALES"
export const GET_SALES_SUCCESS = "GET_SALES_SUCCESS"
export const GET_SALES_FAIL = "GET_SALES_FAIL"



export const ADD_NEW_SALE = "ADD_NEW_SALE"
export const ADD_SALE_SUCCESS = "ADD_SALE_SUCCESS"
export const ADD_SALE_FAIL = "ADD_SALE_FAIL"

export const UPDATE_SALE = "UPDATE_SALE"
export const UPDATE_SALE_SUCCESS = "UPDATE_SALE_SUCCESS"
export const UPDATE_SALE_FAIL = "UPDATE_SALE_FAIL"